version: '3'
services:
  disCom:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .: C:\Users\user\Desktop\disCom
    environment:
      - GOPATH=C:\Users\user\Desktop\disCom
    command: go run main.go
